# Etapa 1: Construcción del JAR con Maven
FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Imagen liviana para ejecución
FROM openjdk:17-jdk-slim

WORKDIR /app
COPY --from=builder /app/target/auth-service-0.0.1.jar auth-service.jar

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "auth-service.jar"]
LABEL authors="Charly Bustamante"
