spring.application.name=auth-service
server.address=0.0.0.0
server.port=8090

# JWT
security.jwt.private.key=46fd06bcde135409926e67bd3ede1b1b55f253a963aa06076eb6f0cbd7f49189
security.jwt.user.generator=CHARLY-SECURITY


#Configuraciones de seguridad
spring.security.user.name=carlos
spring.security.user.password=123
spring.security.user.roles=ADMIN

#Configuraciones de OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23liO4tESNuaogDUMw
spring.security.oauth2.client.registration.github.client-secret=ef359e2becda83947bbdbcb6aed4bed27b883a96