spring.application.name=SecurityRoles

# Configuraciones de seguridad
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASS}

# Configuraciones de Base de Datos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASS}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Confifuraciones de JWT
security.jwt.private.key= ${PRIVATE_KEY}
# CHARLY-SECURITY
security.jwt.user.generator=${USER_GENERATOR}