spring:
  application:
    name: productos
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/almacen_productos
    username: root
    password: ""

server:
  port: 8085
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    private:
      key: 46fd06bcde135409926e67bd3ede1b1b55f253a963aa06076eb6f0cbd7f49189
    user:
      generator: CHARLY-SECURITY      
